### ISSUE TITLE
important information is missing in documentation 

### ISSUE THREAD

**Issue by anschuetz** [NU-ITS/Exhibit#10]
Hello everyone :)

I desperately try to configure the app via apple-profilemanager mdm.  But it keeps demanding an valid configuration.
So I think, my .plist-File is not valid AND/OR the "Paket-ID" is wrong.

Could you add the missing information to the documentation? 
That would be great :)
Best regards,
Jesko

**Comment by thompol** [comment]
Maybe add a full example config to the manual? Same problem here.

**Comment by anschuetz** [comment]
Hello together...
Some time passed :) and meanwhile I managed to get things to show what I like. BUT:
Since Apple-Profilemanager is no option anymore, I have to migrate to Jamf. The same xml does not work. Jamf doesn't tell me that something is wrong with xml (which it does if I do errors) but exhibit keeps saying "ERROR - Data URL was not supplied".

my plist looks like this: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">  
  <dict>
    <key>edu.nebraska.ImageViewer.dataURL</key> 
      <string>https://removed.for.privacy/atv-inhalte.csv</string>
    <key>edu.nebraska.ImageViewer.imageTimer</key>
      <integer>10</integer>
    <key>edu.nebraska.ImageViewer.airplayViewHide</key>
      <false/>
    <key>edu.nebraska.ImageViewer.airplayViewHideOnVideo</key>
      <true/>
    <key>edu.nebraska.ImageViewer.airplayViewTimer</key>
       <integer>25</integer>
    <key>edu.nebraska.ImageViewer.dataCheckTimer</key>
       <integer>180</integer>
    <key>edu.nebraska.ImageViewer.defaultBackground</key>
       <string>DefaultBackgroundNoLogo</string>
    <key>edu.nebraska.ImageViewer.airplayDescription</key>
      <string>Nur Lehrkräfte und von diesen beauftragte Schüler:innen dürfen sich mit dem ATV verbinden!</string>
    <key>edu.nebraska.ImageViewer.airplayViewPositionX</key>
      <integer>1354</integer>
    <key>edu.nebraska.ImageViewer.airplayViewPositionY</key>
       <integer>638</integer>
    <key>edu.nebraska.ImageViewer.airplayViewMovement</key>
      <string>Slide</string>
    <key>edu.nebraska.ImageViewer.playVideosInFull</key>
      <true/>
    <key>edu.nebraska.ImageViewer.playVideosWithAudio</key>
      <true/>
 </dict>
</plist>
```
I tried to remove the first two lines and start with <plist...  but no success.
Where is the problem?

It would be great if anybody was helping me out :)

Best regards 
Jesko

**Comment by anschuetz** [comment]
Ok, talking to myself:  you have to select the configuration while adding the app to the device in jamf. If you install the app first and then create the configuration it doesn't work.

Hope someone will find this useful...
