### ISSUE TITLE
Delayed content load when locked into Single App Mode

### ISSUE THREAD

**Issue by qharouff** [NU-ITS/Exhibit#7]
Issue with content loading after a reboot of an Apple TV with Exhibit locked into Single App Mode. It seems that content loaded is delayed or never loads upon reboot. When Single App Mode profile is removed and re-added, the Exhibit reloads and displays content properly. It seems to take various amounts of time to load the content.

I am currently unable to debug with Xcode as console logging stops working properly when Apple TV is locked into Single App Mode.

**Comment by qharouff** [comment]
Ticket has been opened with Apple and I will hopefully be able to find a resolution to this issue soon.

**Comment by idominiki** [comment]
Any news on this?

**Comment by GrafZahl02** [comment]
Thanks for this great app. 
We do have the same problem. I had to set the timer (edu.nebraska.ImageViewer.dataCheckTimer) to 10 seconds for a moderate time of the black "starting page". After these 10 seconds the csv loads again and the slideshow begins. I think this is only a quick and dirty solution, but maybe you can add a short delay after reboot?
At the end I want to say, that overall this app is really nice and a great benefit for our school.

**Comment by idominiki** [comment]
@GrafZahl02 Thanks for this workaround! I don't look much at the time attributes 😉 

And sure: @qharouff @NU-ITS: Thanks for this great App! It's a huge benefit for our displays in the schools (about 350)!

**Comment by qharouff** [comment]
I don't have an update on this issue but it does seem to be something that has resurfaced in our fleet. I'm going to put some effort into finding a solution in the coming days. Will update with any findings. Thanks!

**Comment by qharouff** [comment]
This issue should be resolved in the upcoming 1.10.0 release.
